name: autorelease

on:
  push:
    branches:
      - master
      - teste

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit:"
          echo "${{ github.event.head_commit.message }}"
