name: autoreleasee

on:
  push:
    branches:
      - master
      - teste

jobs:
  release-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit: ${{github.event.head_commit.message}}"
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Instalar dependências
        run: npm i
      - name: Executar semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  deploy-prod:
    needs: release-prod
    if: ${{needs.release-prod.result == 'failure'}}
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Resultado: ${{ needs.release-prod.result }}" 
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit: ${{github.event.head_commit.message}}"

  release-test:
    if: github.ref == 'refs/heads/teste'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit: ${{github.event.head_commit.message}}"
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Instalar dependências
        run: npm i
      - name: Executar semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  deploy-test:
    needs: release-test
    if: ${{needs.release-test.result == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Resultado: ${{ needs.release-test.result }}" 
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit:"
          echo "MASTERRRRRRRRRRRR"
