name: autorelease

on:
  push:
    branches:
      - master
      - teste

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações do merge
        run: |
          echo "Branch destino: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem do commit:"
          echo "Secretgithub token: ${{ secrets.GITHUB_TOKEN}}"
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Instalar dependências
        run: npm i
      - name: Executar semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Forçar release da test como pre-release
        if: github.ref == 'refs/heads/test'
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          gh release edit "$VERSION" --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
